
environment:
  matrix:
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    platform: x64
#    qtver: 5.6
#    qtbin: msvc2015_64
#    cname: win64_vs2015
#    msvcname: Visual Studio 14 2015 Win64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    qtver: 5.9
    qtbin: msvc2017_64
    cname: win64_vs2017
    msvcname: Visual Studio 15 2017 Win64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    qtver: 5.11
    qtbin: msvc2017_64
    cname: win64_vs2017
    msvcname: Visual Studio 15 2017 Win64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    qtver: 5.12
    qtbin: msvc2017_64
    cname: win64_vs2017
    msvcname: Visual Studio 15 2017 Win64
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#    platform: x64
#    qtver: 5.14
#    qtbin: msvc2019_64
#    cname: win64_vs2019
#    msvcname: Visual Studio 16 2019 Win64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x64
    qtver: 5.15
    qtbin: msvc2019_64
    cname: win64_vs2019
    msvcname: Visual Studio 16 2019 Win64
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    platform: x86
#    qtver: 5.6
#    qtbin: mingw49_32
#    cname: mingw
#    #msvcname: mingw32 Win32
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x86
    qtver: 5.9
    qtbin: mingw53_32
    cname: mingw
    #msvcname: mingw32 Win32
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x86
    qtver: 5.11
    qtbin: mingw53_32
    cname: mingw
    #msvcname: mingw32 Win32
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    platform: x64
#    qtver: 5.11
#    qtbin: mingw73_64
#    cname: mingw64
#    #msvcname: mingw32 Win32
     
install:
  - set QTDIR=C:\Qt\%qtver%\%qtbin%\bin
  - set PATH=%QTDIR%;c:\qt\tools\QtInstallerFramework\3.0\bin;%PATH%
  - if %cname%==mingw set PATH=c:\qt\tools\mingw530_32\bin;%PATH%
  - if %cname%==mingw64 set PATH=c:\qt\tools\mingw730_64\bin;%PATH%
  - if %cname%==mingw set make=mingw32-make.exe
  - if %cname%==mingw64 set make=mingw32-make.exe
  - if %cname%==win64_vs2017 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if %cname%==win64_vs2019 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if not %cname%==mingw set make=nmake.exe

build_script:
  - cd src
  
  # *** build application ***
  - qmake cliphist2.pro
  - '%make%'
  - cd release
  
  # *** execute simple self test ***
  - cliphist2 --selftest
  
  # *** create installer for deployment ***
  - mkdir ..\..\dist\packages\de.mneuroth.cliphist2\data
  - copy cliphist2.exe ..\..\dist\packages\de.mneuroth.cliphist2\data
  - copy ..\cliphist2_256x256.ico ..\..\dist\packages\de.mneuroth.cliphist2\data
  - copy ..\cliphist2_512x512.ico ..\..\dist\packages\de.mneuroth.cliphist2\data
  - copy ..\cliphist2_512x512.png ..\..\dist\packages\de.mneuroth.cliphist2\data
  - cd ..\..\dist\packages\de.mneuroth.cliphist2\data
  - dir c:\Qt
  - dir
  - where windeployqt
  - windeployqt --release --no-system-d3d-compiler cliphist2.exe
  - dir
  - cd ..\..\..\..\dist
  - path
  - set PATH=%PATH%;c:\Qt\Tools\4.2\bin
  - dir c:\Qt\Tools\
  - dir c:\Qt\Tools\QtInstallerFramework
  - where binarycreator
  - binarycreator -c config\config.xml -p packages Cliphist2_Installer_%cname%_qt%qtver%.exe
  - appveyor PushArtifact Cliphist2_Installer_%cname%_qt%qtver%.exe
  - dir 
 
deploy:
  provider: GitHub
  auth_token:
    secure: wDEI4YGtqf1MiuNbtiv/zZ+rfuEmfO/PxfRfZC5gjtFDez3qDk6Vv9+auWwTstyZ
  artifact: Cliphist2_Installer_%cname%_qt%qtver%.exe 
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true        
