
matrix:
  include:    
    - os: linux
      dist: xenial
      language: cpp
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - qt5-default
          - qtbase5-private-dev
          - qttools5-dev-tools
          - libxcb-keysyms1-dev
      script:
      - ./build_ci.sh
      - cd src
      - ls -lrt 
      #- ./cliphist2 --selftest
    
    - os: osx
      language: cpp
      compiler: clang
      before_install:
      - brew update
      - brew install qt
      - export PATH=/usr/local/opt/qt/bin:$PATH
      script:
      - ./build_ci.sh
      - cd src
      - ls -lrt cliphist2.app
      - ls -lrt cliphist2.app/Contents
      - ls -lrt cliphist2.app/Contents/MacOS
      #- ./cliphist2.app --selftest
      
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
