
matrix:
  include:    
    - os: linux
      dist: xenial
      language: cpp
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - qt5-default
          - qtbase5-private-dev
          - qttools5-dev-tools
          - libxcb-keysyms1-dev
      services:
      - xvfb
      script:
      - ./build_ci.sh
      - cd src
      - ls -lrt 
      - xvfb-run -e /dev/stdout --auto-servernum --server-num=1 ./cliphist2 --selftest
    
    - os: osx
      language: cpp
      compiler: clang
      before_install:
      - brew update
      - brew install qt
      - export PATH=/usr/local/opt/qt/bin:$PATH
      script:
      - ./build_ci.sh
      - cd src
      - ls -lrt
      - ./cliphist2.app/Contents/MacOS/cliphist2 --selftest 
      #- ls -lrt cliphist2.app
      #- ls -lrt cliphist2.app/Contents
      #- ls -lrt cliphist2.app/Contents/MacOS
      #- ./cliphist2.app --selftest
      - macdeployqt cliphist2.app/ -dmg
      #- mkdir ../dist/packages/de.mneuroth.cliphist2/data
      #- cp -R cliphist2.app ../dist/packages/de.mneuroth.cliphist2/data/
      #- binarycreator --offline-only -c ../dist/config/config.xml -p ../dist/packages cliphist2_installer
      #- macdeployqt cliphist2.app/ -dmg
      - ls -lrt
      deploy:
        provider: releases
        api_key:
          secure: Ant/0i6hAVbNLNeYMiD0/uqS4HRgdT1b2mVsu8MGppxXGmhAn5Pb+Dv7xRaRiXTuympjI7WHtXDapQsHnMKNWXlv8lizSojVzvzNalh+V8+sn20p7WIXz6QBVy5Fba6CGRm+0EOyYc//leIZMBAENlRXIGKz39ShSl76Z2NwMSRVlLTybnuE716J9xbB/1YzdADE3N4jxF+xd7BnKiPJF9pTQUdgBpFLG9pAVkzKVRsplN+lmysVK1Iwow0z44RqZPSMvFHJLI5IdHgUQ90uDkh5Hnt2WgzonQod3Uy3nKJ3GW58FFoMkzoupA8ySWiJLIfOMNZ47VUE6/6sHRNlpF+g3EEXjKur0HYl488LT0c1yvUtWZUUQeIqW6j5BlCrTCa38Gz1M6I1AH2/NsUeZQ2/4aUAoIpOjyiKOrwdBHKQyPvVlpDxBcpzqRc6a0qlTOkSlWGp83+T7qYatq1pnc56NinUHyePWVheWGQT3WWplaYPflXYMlqNIUmdHz4FUomtFpM8tFzizOhjfLbveF4Od1m0ETLLjIRs1V7IstYW2LXov2yMNSsyAZ3hT2f1K0092U7kfnJisFOClHaA+INZ4KcpXYk0QRqGcBXUR3YN9cfO/qSXUElKmkAnBR3AoJY0CRQ6x7l9NGZi5tVyVKLyxAFyCUcRyZSHL/V3Hck=
        file: src/cliphist2.dmg
        skip_cleanup: true
        on:
          tags: true
      
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
