# Multi language build script for cshaarp and c++

matrix:
  include:    
    - os: linux
      language: cpp
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - qt5-default
          - qttools5-dev-tools
      script:
      - ./build_ci.sh
    
    - os: osx
      language: cpp
      compiler: clang
      script:
      - ./build_ci.sh
    
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/qt/bin:$PATH; fi
  
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
