name: Windows CI

on:
  push:
    branches: [ master ]
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

jobs:

  windows_5_15_2_msc_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: jurplel/install-qt-action@v2
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '5.15.2'
        # Host platform
        host: # optional
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: 'win64_msvc2019_64'
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: ''
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
        tools: 'tools_ifw,4.4.1-0-202206210642,qt.tools.ifw.44'
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose
    - name: Install Qt and compile
      run: |
        cd 
        dir
        d:
        dir
        cl
        cd src
        dir
        qmake -r cliphist2.pro
        dir
        nmake
        dir
        dir release
        dir debug
        cd release
        dir
        mkdir ..\..\dist\packages\de.mneuroth.cliphist2\data
        copy cliphist2.exe ..\..\dist\packages\de.mneuroth.cliphist2\data
        copy ..\cliphist2_256x256.ico ..\..\dist\packages\de.mneuroth.cliphist2\data
        copy ..\cliphist2_512x512.ico ..\..\dist\packages\de.mneuroth.cliphist2\data
        copy ..\cliphist2_512x512.png ..\..\dist\packages\de.mneuroth.cliphist2\data
        cd ..\..\dist\packages\de.mneuroth.cliphist2\data
        where windeployqt
        windeployqt --release --no-system-d3d-compiler cliphist2.exe
        dir
        cd ..\..\..\..\dist
        set PATH=%PATH%;c:\Qt\Tools\QtInstallerFramework\4.4\bin
        where binarycreator
        binarycreator -c config\config.xml -p packages Cliphist2_Installer_win_qt5.15.exe
        dir
        
  windows_6_3_1_msc_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: jurplel/install-qt-action@v2
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '6.3.1'
        # Host platform
        host: # optional
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: 'win64_msvc2019_64'
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: 'qt5compat'
        # Force a Qt mirror in case the default is not working
        #mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
        #mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        #setup-python: 'true'
        #tools-only: 'false'
        #aqtversion: '==0.10.0'
        #py7zrversion: '==0.11.0'
        #extra: '--external 7z'
        tools: 'tools_ifw,4.4.1-0-202206210642,qt.tools.ifw.44'
    - name: Install 7Zip PowerShell Module
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose
    - name: Install Qt and compile
      run: |
        cd 
        dir
        d:
        dir
        cl
        cd src
        dir
        qmake -r cliphist2.pro
        dir
        nmake
        dir
        dir release
        dir debug
        cd release
        dir
        mkdir ..\..\dist\packages\de.mneuroth.cliphist2\data
        copy cliphist2.exe ..\..\dist\packages\de.mneuroth.cliphist2\data
        copy ..\cliphist2_256x256.ico ..\..\dist\packages\de.mneuroth.cliphist2\data
        copy ..\cliphist2_512x512.ico ..\..\dist\packages\de.mneuroth.cliphist2\data
        copy ..\cliphist2_512x512.png ..\..\dist\packages\de.mneuroth.cliphist2\data
        cd ..\..\dist\packages\de.mneuroth.cliphist2\data
        where windeployqt
        windeployqt --release --no-system-d3d-compiler cliphist2.exe
        dir
        cd ..\..\..\..\dist
        set PATH=%PATH%;c:\Qt\Tools\QtInstallerFramework\4.4\bin
        where binarycreator
        binarycreator -c config\config.xml -p packages Cliphist2_Installer_win_qt5.15.exe
        dir
